import type { Metadata } from "next";
import stylex from "@stylexjs/stylex";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const styles = stylex.create({
	root: {
		scrollBehavior: "smooth",
	},
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html {...stylex.props(styles.root)} lang="en">
			<body>{children}</body>
		</html>
	);
}
